console.log('Fuck you sir')
console.log('----------------')
console.log('Fuck you again----')
console.log('Fuck you sir')
console.log('----------------')
console.log('Fuck you again----')
console.log('Fuck you sir')
console.log('----------------')
console.log('Fuck you again----')